
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('regions_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('regions_table').insert([
       
	{ "regions_name": "ASIA", "country_id": 3 },
	{ "regions_name": "ASIA", "country_id": 4 },
	{ "regions_name": "ASIA", "country_id": 5 },
	{ "regions_name": "Cruize ship", "country_id": 6 },
	{ "regions_name": "ASIA", "country_id": 7 },
	{ "regions_name": "ASIA", "country_id": 8 },
	{ "regions_name": "N. AMERICA", "country_id": 9 },
	{ "regions_name": "ASIA", "country_id": 10 },
	{ "regions_name": "ASIA", "country_id": 11 },
	{ "regions_name": "ASIA", "country_id": 12 },
	{ "regions_name": "ASIA", "country_id": 13 },
	{ "regions_name": "ASIA", "country_id": 14 },
	{ "regions_name": "EUROPE", "country_id": 15 },
	{ "regions_name": "OCEANIA", "country_id": 16 },
	{ "regions_name": "ASIA", "country_id": 17 },
	{ "regions_name": "N. AMERICA", "country_id": 18 },
	{ "regions_name": "ASIA", "country_id": 19 },
	{ "regions_name": "EUROPE", "country_id": 20 },
	{ "regions_name": "ASIA", "country_id": 21 },
	{ "regions_name": "EUROPE", "country_id": 22 },
	{ "regions_name": "ASIA", "country_id": 23 },
	{ "regions_name": "ASIA", "country_id": 24 },
	{ "regions_name": "ASIA", "country_id": 25 },
	{ "regions_name": "EUROPE", "country_id": 26 },
	{ "regions_name": "EUROPE", "country_id": 27 },
	{ "regions_name": "ASIA", "country_id": 28 },
	{ "regions_name": "EUROPE", "country_id": 29 },
	{ "regions_name": "EUROPE", "country_id": 30 },
	{ "regions_name": "EUROPE", "country_id": 31 },
	{ "regions_name": "AFRICA", "country_id": 32 },
	{ "regions_name": "ASIA", "country_id": 33 },
	{ "regions_name": "ASIA", "country_id": 34 },
	{ "regions_name": "ASIA", "country_id": 35 },
	{ "regions_name": "ASIA", "country_id": 36 },
	{ "regions_name": "ASIA", "country_id": 37 },
	{ "regions_name": "ASIA", "country_id": 38 },
	{ "regions_name": "ASIA", "country_id": 39 },
	{ "regions_name": "ASIA", "country_id": 40 },
	{ "regions_name": "EUROPE", "country_id": 41 },
	{ "regions_name": "EUROPE", "country_id": 42 },
	{ "regions_name": "EUROPE", "country_id": 43 },
	{ "regions_name": "AFRICA", "country_id": 44 },
	{ "regions_name": "S. AMERICA", "country_id": 45 },
	{ "regions_name": "EUROPE", "country_id": 46 },
	{ "regions_name": "ASIA", "country_id": 47 },
	{ "regions_name": "EUROPE", "country_id": 48 },
	{ "regions_name": "ASIA", "country_id": 49 },
	{ "regions_name": "EUROPE", "country_id": 50 },
	{ "regions_name": "EUROPE", "country_id": 51 },
	{ "regions_name": "EUROPE", "country_id": 52 },
	{ "regions_name": "EUROPE", "country_id": 53 },
	{ "regions_name": "EUROPE", "country_id": 54 },
	{ "regions_name": "EUROPE", "country_id": 55 },
	{ "regions_name": "AFRICA", "country_id": 56 },
	{ "regions_name": "EUROPE", "country_id": 57 },
	{ "regions_name": "OCEANIA", "country_id": 58 },
	{ "regions_name": "EUROPE", "country_id": 59 },
	{ "regions_name": "ASIA", "country_id": 60 },
	{ "regions_name": "C. AMERICA", "country_id": 61 },
	{ "regions_name": "EUROPE", "country_id": 62 },
	{ "regions_name": "EUROPE", "country_id": 63 },
	{ "regions_name": "ASIA", "country_id": 64 },
	{ "regions_name": "S. AMERICA", "country_id": 65 },
	{ "regions_name": "EUROPE", "country_id": 66 },
	{ "regions_name": "EUROPE", "country_id": 67 },
	{ "regions_name": "EUROPE", "country_id": 68 },
	{ "regions_name": "C. AMERICA", "country_id": 69 },
	{ "regions_name": "ASIA", "country_id": 70 },
	{ "regions_name": "ASIA", "country_id": 71 },
	{ "regions_name": "EUROPE", "country_id": 72 },
	{ "regions_name": "EUROPE", "country_id": 73 },
	{ "regions_name": "ASIA", "country_id": 74 },
	{ "regions_name": "AFRICA", "country_id": 75 },
	{ "regions_name": "AFRICA", "country_id": 76 },
	{ "regions_name": "EUROPE", "country_id": 77 },
	{ "regions_name": "ASIA", "country_id": 78 },
	{ "regions_name": "AFRICA", "country_id": 79 },
	{ "regions_name": "EUROPE", "country_id": 80 },
	{ "regions_name": "S. AMERICA", "country_id": 81 },
	{ "regions_name": "EUROPE", "country_id": 82 },
	{ "regions_name": "S. AMERICA", "country_id": 83 },
	{ "regions_name": "EUROPE", "country_id": 84 },
	{ "regions_name": "EUROPE", "country_id": 85 },
	{ "regions_name": "EUROPE", "country_id": 86 },
	{ "regions_name": "EUROPE", "country_id": 87 },
	{ "regions_name": "ASIA", "country_id": 88 },
	{ "regions_name": "AFRICA", "country_id": 89 },
	{ "regions_name": "EUROPE", "country_id": 90 },
	{ "regions_name": "AFRICA", "country_id": 91 },
	{ "regions_name": "ASIA", "country_id": 92 },
	{ "regions_name": "EUROPE", "country_id": 93 },
	{ "regions_name": "EUROPE", "country_id": 94 },
	{ "regions_name": "AFRICA", "country_id": 95 },
	{ "regions_name": "S. AMERICA", "country_id": 96 },
	{ "regions_name": "S. AMERICA", "country_id": 97 },
	{ "regions_name": "ASIA", "country_id": 98 },
	{ "regions_name": "EUROPE", "country_id": 99 },
	{ "regions_name": "S. AMERICA", "country_id": 100 },
	{ "regions_name": "EUROPE", "country_id": 101 },
	{ "regions_name": "C. AMERICA", "country_id": 102 },
	{ "regions_name": "ASIA", "country_id": 103 },
	{ "regions_name": "EUROPE", "country_id": 104 },
	{ "regions_name": "EUROPE", "country_id": 105 },
	{ "regions_name": "EUROPE", "country_id": 106 },
	{ "regions_name": "ASIA", "country_id": 107 },
	{ "regions_name": "ASIA", "country_id": 108 },
	{ "regions_name": "C. AMERICA", "country_id": 109 },
	{ "regions_name": "AFRICA", "country_id": 110 },
	{ "regions_name": "AFRICA", "country_id": 111 },
	{ "regions_name": "N. AMERICA", "country_id": 112 },
	{ "regions_name": "ASIA", "country_id": 113 },
	{ "regions_name": "S. AMERICA", "country_id": 114 },
	{ "regions_name": "C. AMERICA", "country_id": 115 },
	{ "regions_name": "AFRICA", "country_id": 116 },
	{ "regions_name": "OCEANIA", "country_id": 117 },
	{ "regions_name": "S. AMERICA", "country_id": 118 },
	{ "regions_name": "C. AMERICA", "country_id": 119 },
	{ "regions_name": "C. AMERICA", "country_id": 120 },
	{ "regions_name": "S. AMERICA", "country_id": 121 }

      ]);
    });
};
